on: [push]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: gremid/tei-stylesheets-action@v7.54.0
        with:
          transform: teitorelaxng
          source: ./tei_lite.odd
          target: ./public/tei_lite.rng
      - uses: gremid/tei-stylesheets-action@v7.54.0
        with:
          transform: teitornc
          source: ./tei_lite.odd
          target: ./public/tei_lite.rnc
      - uses: gremid/tei-stylesheets-action@v7.54.0
        with:
          transform: teitoschematron
          source: ./tei_lite.odd
          target: ./public/tei_lite.sch.xsl
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
