on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - uses: gremid/tei-stylesheets-action@230e214a65f7f50273b3d6da5f648ec9564c4c37
        with:
          transform: teitorelaxng
          source: ./tei_lite.odd
          target: ./public/tei_lite.rng
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
